name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests # main execution step
        run: npx playwright test

      # --- Debugging Steps for Artifact Upload ---
      
      - name: List 'playwright-report' directory content (should be empty/non-existent)
        run: ls -la playwright-report/ || true # '|| true' prevents failure if dir doesn't exist
        if: always() # Run even if previous steps fail

      - name: List 'reports/html' directory content (THIS is where your report should be!)
        run: ls -la reports/html/
        if: always() # Run even if previous steps fail

      # --- Actual Artifact Upload Step ---

      - name: Upload Playwright report
        if: always() 
        uses: actions/upload-artifact@v4.6.2
        with:
          name: playwright-report
          path: reports/html/
          if-no-files-found: error

      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"