name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report (optional)
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: playwright-report
          path: playwright-report/

      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"

      - name: Run Playwright tests
        run: npx playwright test

      - name: List Playwright  report directory content
        run: |
          ls -la playwright-report/
          # You can also use 'find playwright-report/' for more details
        # Add an 'if' condition if you only want this to run on failure
        if: always()

      - name: Upload Playwright report (optional)
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: playwright-report
          path: playwright-report
          # Add this to explicitky error if no files are found
          if-no-files-found: error

